#!/usr/bin/env php
<?php
/**
 * @copyright (c) JTL-Software-GmbH
 * @license       http://jtl-url.de/jtlshoplicense
 */

require_once __DIR__.'/includes/globalinclude.php';
if (file_exists(__DIR__.'/install/vendor/autoload.php')) {
    require_once __DIR__.'/install/vendor/autoload.php';
}

$application = new \JTL\Console\Application();
$application->run();