<?php

/**
 * Reworked frontend texts
 *
 * @author mh
 * @created Wed, 20 Nov 2019 11:08:00 +0200
 */

use JTL\Update\IMigration;
use JTL\Update\Migration;

/**
 * Class Migration_20191120110800
 */
class Migration_20191120110800 extends Migration implements IMigration
{
    protected $author      = 'mh';
    protected $description = 'Reworked frontend texts';

    /**
     * @return mixed|void
     * @throws Exception
     */
    public function up()
    {
        $this->setLocalization('ger', '﻿global', 'aaSelectBTN', 'Auswählen');
        $this->setLocalization('ger', 'global', 'accountCreated', 'Ihr Kundenkonto wurde erstellt.');
        $this->setLocalization('ger', 'global', 'accountInactive', 'Ihr Kundenkonto wurde deaktiviert.');
        $this->setLocalization('ger', 'global', 'accountLocked', 'Ihr Kundenkonto wurde gesperrt.');
        $this->setLocalization('ger', 'global', 'adminMaintenanceMode', 'Der Wartungsmodus des Onlineshops ist aktiv. Da Sie als Administrator angemeldet sind, können Sie trotzdem alle Funktionen des Onlineshops bedienen.');
        $this->setLocalization('ger', 'global', 'ajaxcheckoutChangemethode', 'Ändern');
        $this->setLocalization('ger', 'global', 'ajaxLoading', 'Wird geladen…');
        $this->setLocalization('ger', 'global', 'ampelGelb', 'Knapper Lagerbestand');
        $this->setLocalization('ger', 'global', 'ampelGruen', 'Sofort verfügbar');
        $this->setLocalization('ger', 'global', 'ampelRot', 'Momentan nicht verfügbar');
        $this->setLocalization('ger', 'global', 'applyChanges', 'Änderungen übernehmen');
        $this->setLocalization('ger', 'global', 'asc', 'aufsteigend');
        $this->setLocalization('ger', 'global', 'basketCustomerWhoBoughtXBoughtAlsoY', 'Kunden kauften dazu folgende Artikel');
        $this->setLocalization('ger', 'global', 'blockedEmail', 'E-Mail-Adresse ist gesperrt.');
        $this->setLocalization('ger', 'global', 'categoryoverviewSub', 'Wählen Sie eine Kategorie!');
        $this->setLocalization('ger', 'global', 'clickImgToZoom', 'Klicken Sie auf das Bild, um es in der Galerieansicht zu öffnen.');
        $this->setLocalization('ger', 'global', 'compareListNoItems', 'Es befinden sich noch keine Artikel auf Ihrer Vergleichsliste.');
        $this->setLocalization('ger', 'global', 'configure', 'Konfigurieren');
        $this->setLocalization('ger', 'global', 'copyright', '© 2019');
        $this->setLocalization('ger', 'global', 'copyrightName', 'JTL-Shop');
        $this->setLocalization('ger', 'global', 'counter', 'Besucherzähler');
        $this->setLocalization('ger', 'global', 'couponErr1', 'Coupon ist nicht aktiv.');
        $this->setLocalization('ger', 'global', 'couponErr10', 'Der Coupon gilt nicht für die angegebene Lieferadresse.');
        $this->setLocalization('ger', 'global', 'couponErr12', 'Der Coupon gilt nicht für den aktuellen Warenkorb (gilt nur für bestimmte Hersteller).');
        $this->setLocalization('ger', 'global', 'couponErr2', 'Der Coupon ist nicht mehr gültig (Datum abgelaufen).');
        $this->setLocalization('ger', 'global', 'couponErr3', 'Der Coupon ist nicht mehr gültig.');
        $this->setLocalization('ger', 'global', 'couponErr4', 'Der für diesen Coupon benötigte Mindestbestellwert wurde noch nicht erreicht.');
        $this->setLocalization('ger', 'global', 'couponErr5', 'Der Coupon gilt nicht für die aktuelle Kundengruppe.');
        $this->setLocalization('ger', 'global', 'couponErr6', 'Die maximale Anzahl der Verwendungen für den Coupon wurde erreicht.');
        $this->setLocalization('ger', 'global', 'couponErr7', 'Der Coupon gilt nicht für den aktuellen Warenkorb (gilt nur für bestimmte Artikel).');
        $this->setLocalization('ger', 'global', 'couponErr8', 'Der Coupon gilt nicht für den aktuellen Warenkorb (gilt nur für bestimmte Kategorien).');
        $this->setLocalization('ger', 'global', 'couponErr9', 'Der Coupon gilt nicht für Ihr Kundenkonto.');
        $this->setLocalization('ger', 'global', 'couponErr99', 'Unbekannter Coupon-Fehler. Bitte wiederholen Sie die Eingabe oder wenden Sie sich ggf. an den Support.');
        $this->setLocalization('ger', 'global', 'couponSucc1', 'Ihr Versandkostenfrei-Coupon wurde für folgende Lieferländer freigeschaltet:');
        $this->setLocalization('ger', 'global', 'csrfValidationFailed', 'Die Anfrage konnte nicht verarbeitet werden. Der Grund hierfür kann sein, dass die Anfrage von einer unbekannten Quelle gestellt wurde oder die Website-Sitzung zwischenzeitlich abgelaufen ist. Bitte versuchen Sie es erneut.');
        $this->setLocalization('ger', 'global', 'dateOfIssue', 'Voraussichtliches Erscheinungsdatum:');
        $this->setLocalization('ger', 'global', 'delete', 'Entfernen');
        $this->setLocalization('ger', 'global', 'details', 'Zum Artikel');
        $this->setLocalization('ger', 'global', 'dlErrorCustomerNotMatch', 'Der angemeldete Kunde und die Berechtigung der Download-Datei stimmen nicht überein.');
        $this->setLocalization('ger', 'global', 'dlErrorDownloadLimitReached', 'Die maximale Download-Anzahl wurde erreicht.');
        $this->setLocalization('ger', 'global', 'dlErrorDownloadNotFound', 'Der Artikel mit diesem Download existiert nicht.');
        $this->setLocalization('ger', 'global', 'dlErrorOrderNotFound', 'Ihre Bestellung konnte nicht gefunden werden.');
        $this->setLocalization('ger', 'global', 'dlErrorValidityReached', 'Die Gültigkeitsdauer wurde überschritten.');
        $this->setLocalization('ger', 'global', 'dlErrorWrongParameter', 'Die Parameter sind ungültig. Es wurde keine Datei zu diesem Download-Link gefunden.');
        $this->setLocalization('ger', 'global', 'downloadLimit', 'Download-Zahl');
        $this->setLocalization('ger', 'global', 'downloadPending', 'Zahlungseingang ausstehend');
        $this->setLocalization('ger', 'global', 'ean', 'GTIN');
        $this->setLocalization('ger', 'global', 'eanNotExist', 'Leider existiert in unserem Sortiment kein Artikel mit folgender Artikelnummer/GTIN:');
        $this->setLocalization('ger', 'global', 'edit', 'Bearbeiten');
        $this->setLocalization('ger', 'global', 'else', 'sonst');
        $this->setLocalization('ger', 'global', 'emailadress', 'E-Mail-Adresse');
        $this->setLocalization('ger', 'global', 'estimateShippingCostsNote', 'Die Versandkosten können erst ermittelt werden, wenn sich Artikel im Warenkorb befinden.');
        $this->setLocalization('ger', 'global', 'expressionHasTo', 'Der Suchbegriff muss mindestens aus');
        $this->setLocalization('ger', 'global', 'filterAndSort', 'Filter und Sortierung');
        $this->setLocalization('ger', 'global', 'findProduct', 'Artikel suchen');
        $this->setLocalization('ger', 'global', 'firstReview', 'Geben Sie die erste Bewertung für diesen Artikel ab und helfen Sie anderen bei der Kaufentscheidung!');
        $this->setLocalization('ger', 'global', 'freeGiftFrom1', 'Ab Bestellwert von');
        $this->setLocalization('ger', 'global', 'freeGiftFromOrderValue', 'Im Warenkorb können Sie aus folgenden Gratisgeschenken wählen, sofern Ihr Warenkorb den erforderlichen Warenwert erreicht hat.');
        $this->setLocalization('ger', 'global', 'freeGiftFromOrderValueBasket', 'Wählen Sie ein Gratisgeschenk:');
        $this->setLocalization('ger', 'global', 'incorrectEmail', 'Es existiert kein Kunde mit der angegebenen E-Mail-Adresse. Bitte versuchen Sie es erneut.');
        $this->setLocalization('ger', 'global', 'incorrectEmailPlz', 'Es existiert kein Kunde mit der angegebenen E-Mail-Adresse und PLZ. Bitte versuchen Sie es erneut.');
        $this->setLocalization('ger', 'global', 'incorrectLogin', 'Benutzername und Passwort stimmen nicht überein. Bitte versuchen Sie es erneut.');
        $this->setLocalization('ger', 'global', 'inStock', 'Auf Lager');
        $this->setLocalization('ger', 'global', 'invalidDate', 'Ungültiges Datum');
        $this->setLocalization('ger', 'global', 'invalidDateformat', 'Geben Sie das Datum im Format TT.MM.JJJJ ein, z. B. 04.11.1981.');
        $this->setLocalization('ger', 'global', 'invalidEmail', 'Bitte geben Sie eine gültige E-Mail-Adresse an.');
        $this->setLocalization('ger', 'global', 'invalidInteger', 'Bitte geben Sie eine Zahl ein.');
        $this->setLocalization('ger', 'global', 'invalidTel', 'Bitte geben Sie Ihre Nummer nur in Ziffern ein.');
        $this->setLocalization('ger', 'global', 'invalidToken', 'Der eingegebene Sicherheitscode ist ungültig.');
        $this->setLocalization('ger', 'global', 'invalidURL', 'Bitte geben Sie eine gültige URL ein.');
        $this->setLocalization('ger', 'global', 'language', 'Sprache');
        $this->setLocalization('ger', 'global', 'loginNotActivated', 'Ihr Kundenkonto wurde noch nicht freigeschaltet. Bitte versuchen Sie es zu einem späteren Zeitpunkt erneut.');
        $this->setLocalization('ger', 'global', 'maintenanceModeActive', 'Dieser Onlineshop befindet sich im Wartungsmodus.');
        $this->setLocalization('ger', 'global', 'manufacturer', 'Herstellerübersicht');
        $this->setLocalization('ger', 'global', 'myWishlists', 'Meine Wunschzettel');
        $this->setLocalization('ger', 'global', 'newProducts', 'Neu im Sortiment');
        $this->setLocalization('ger', 'global', 'newsArchiv', 'News-Archiv');
        $this->setLocalization('ger', 'global', 'newsArchivDesc', 'Alle News-Beiträge im Archiv ');
        $this->setLocalization('ger', 'global', 'newsBoxCatOverview', 'News: Kategorien des News-Systems');
        $this->setLocalization('ger', 'global', 'newsBoxMonthOverview', 'News: Monate mit Beiträgen');
        $this->setLocalization('ger', 'global', 'newsletterhistory', 'Newsletter-Archiv');
        $this->setLocalization('ger', 'global', 'newsletterhistoryback', 'Zurück');
        $this->setLocalization('ger', 'global', 'noEntriesAvailable', 'Keine Einträge vorhanden.');
        $this->setLocalization('ger', 'global', 'noFilterResults', 'Für diesen Filter wurden keine Ergebnisse gefunden.');
        $this->setLocalization('ger', 'global', 'noShippingcostsTo', 'Versandkostenfreie Lieferung');
        $this->setLocalization('ger', 'global', 'notAvailableInSelection', 'Ihre Auswahl ist leider nicht verfügbar.');
        $this->setLocalization('ger', 'global', 'oldPrice', 'Alter Preis');
        $this->setLocalization('ger', 'global', 'paginationEntriesPerPage', 'Einträge pro Seite');
        $this->setLocalization('ger', 'global', 'paginationTotalEntries', 'Einträge insgesamt:');
        $this->setLocalization('ger', 'global', 'parseTextNoLinkID', 'Ungültiger Link');
        $this->setLocalization('ger', 'global', 'payWithPaypal', 'Jetzt mit PayPal bezahlen');
        $this->setLocalization('ger', 'global', 'priceHidden', 'Preise nach Anmeldung sichtbar');
        $this->setLocalization('ger', 'global', 'productAddedToCart', 'wurde erfolgreich in den Warenkorb gelegt!');
        $this->setLocalization('ger', 'global', 'productAvailable', 'Verfügbar');
        $this->setLocalization('ger', 'global', 'productNo', 'Artikelnummer');
        $this->setLocalization('ger', 'global', 'productNoEAN', 'Artikelnummer / GTIN');
        $this->setLocalization('ger', 'global', 'productNoExtraShippingNotice', 'Es fallen keine zusätzlichen Versandkosten an.');
        $this->setLocalization('ger', 'global', 'productNotAvailable', 'Artikel vergriffen');
        $this->setLocalization('ger', 'global', 'productsFrom', 'Artikel von');
        $this->setLocalization('ger', 'global', 'productsTaggedAs', 'Artikel mit Tag');
        $this->setLocalization('ger', 'global', 'productsWith', 'Artikel mit');
        $this->setLocalization('ger', 'global', 'questiontoproductSuccessful', 'Ihre Frage wurde erfolgreich übermittelt. Sie werden in Kürze eine E-Mail von uns erhalten.');
        $this->setLocalization('ger', 'global', 'registerNow', 'Jetzt registrieren!');
        $this->setLocalization('ger', 'global', 'resetSelection', 'Auswahl zurücksetzen');
        $this->setLocalization('ger', 'global', 'selectCurrency', 'Bitte wählen Sie eine Währung.');
        $this->setLocalization('ger', 'global', 'selectLang', 'Bitte wählen Sie eine Sprache.');
        $this->setLocalization('ger', 'global', 'selectManufacturer', 'Bitte wählen Sie einen Hersteller.');
        $this->setLocalization('ger', 'global', 'selectUpdateFile', 'Bitte wählen Sie eine Datei aus.');
        $this->setLocalization('ger', 'global', 'shippingTime', 'Errechnete Lieferzeit');
        $this->setLocalization('ger', 'global', 'shippingTimeLP', 'Lieferzeit');
        $this->setLocalization('ger', 'global', 'showAllNewProducts', 'Zeige alle neuen Artikel');
        $this->setLocalization('ger', 'global', 'showAllProductsTaggedWith', 'Zeige alle getaggten Artikel mit');
        $this->setLocalization('ger', 'global', 'showAllTopOffers', 'Zeige alle Top-Angebote');
        $this->setLocalization('ger', 'global', 'showAllUpcomingProducts', 'Zeige alle in Kürze verfügbaren Artikel');
        $this->setLocalization('ger', 'global', 'showProducts', 'Zeige Artikel');
        $this->setLocalization('ger', 'global', 'sitemapNewsCats', 'News-Kategorien');
        $this->setLocalization('ger', 'global', 'sortAvailability', 'Lagerbestand');
        $this->setLocalization('ger', 'global', 'sortEan', 'GTIN');
        $this->setLocalization('ger', 'global', 'sortNameAsc', 'Artikelname von A bis Z');
        $this->setLocalization('ger', 'global', 'sortNameDesc', 'Artikelname von Z bis A');
        $this->setLocalization('ger', 'global', 'sortNewestFirst', 'Neueste zuerst');
        $this->setLocalization('ger', 'global', 'sortPriceAsc', 'Preis aufsteigend');
        $this->setLocalization('ger', 'global', 'sortPriceDesc', 'Preis absteigend');
        $this->setLocalization('ger', 'global', 'specificProducts', 'Besondere Artikel');
        $this->setLocalization('ger', 'global', 'subtotal', 'Summe');
        $this->setLocalization('ger', 'global', 'Suedamerika', 'Südamerika');
        $this->setLocalization('ger', 'global', 'supplierStockNotice', 'Muss bestellt werden. Ab Bestellung lieferbar in %s Tagen.');
        $this->setLocalization('ger', 'global', 'switchToMobileTemplate', 'Möchten Sie diese Website in einer für mobile Endgeräte optimierten Version aufrufen?');
        $this->setLocalization('ger', 'global', 'tagcloud', 'Tag-Wolke');
        $this->setLocalization('ger', 'global', 'tagFilter', 'Tag-Filter');
        $this->setLocalization('ger', 'global', 'topOffer', 'Top-Angebot');
        $this->setLocalization('ger', 'global', 'topOffers', 'Top-Angebote');
        $this->setLocalization('ger', 'global', 'toprating', 'Top bewerteten Artikel');
        $this->setLocalization('ger', 'global', 'topsearch', 'Top-Suchanfragen ');
        $this->setLocalization('ger', 'global', 'toptags', 'Am häufigsten vergebene Tags ');
        $this->setLocalization('ger', 'global', 'ts_classic_text', 'trägt das Trusted Shops Zertifikat mit Käuferschutz. Mehr…');
        $this->setLocalization('ger', 'global', 'ts_comment', 'Als zusätzlichen Service bieten wir Ihnen den Trusted Shops Käuferschutz an. Wir übernehmen alle Kosten dieser Garantie. Sie müssen sich lediglich anmelden.');
        $this->setLocalization('ger', 'global', 'ts_seal_classic_title', 'Klicken Sie auf das Gütesiegel, um die Gültigkeit zu prüfen!');
        $this->setLocalization('ger', 'global', 'ts_signtitle', 'Trusted Shops Gütesiegel – Bitte hier Gültigkeit prüfen!');
        $this->setLocalization('ger', 'global', 'unlimited', 'uneingeschränkt');
        $this->setLocalization('ger', 'global', 'uploadCanceled', 'Der Datei-Upload wurde abgebrochen.');
        $this->setLocalization('ger', 'global', 'uploadEmptyFile', 'Die ausgewählte Datei ist leer.');
        $this->setLocalization('ger', 'global', 'uploadError', 'Der Upload konnte nicht durchgeführt werden. Bitte versuchen Sie es erneut.');
        $this->setLocalization('ger', 'global', 'ustIDCaseFive', 'Die USt-IdNr. ist laut MIAS-Prüfung ungültig.');
        $this->setLocalization('ger', 'global', 'ustIDCaseTwo', 'Die USt-IdNr. weist ein ungültiges Format auf.');
        $this->setLocalization('ger', 'global', 'ustIDCaseTwoB', 'Für Ihr Land sollte die USt-IdNr. das folgende Format aufweisen:');
        $this->setLocalization('ger', 'global', 'ustIDError100', 'Die Länderkennung der USt-IdNr. muss mit zwei Großbuchstaben beginnen.');
        $this->setLocalization('ger', 'global', 'ustIDError110', 'Die USt-IdNr. hat eine ungültige Länge.');
        $this->setLocalization('ger', 'global', 'ustIDError120', 'Die USt-IdNr. entspricht nicht den Vorschriften Ihres Landes!<br>Der Fehler trat hier auf: ');
        $this->setLocalization('ger', 'global', 'ustIDError130', 'Es existiert kein Land mit folgender Kennung: ');
        $this->setLocalization('ger', 'global', 'ustIDError200', 'Der MIAS-Dienst Ihres Landes ist nicht erreichbar bis: ');
        $this->setLocalization('ger', 'global', 'voucher', 'Coupon');
        $this->setLocalization('ger', 'global', 'weightUnit', 'kg');
        $this->setLocalization('ger', 'global', 'wrbform', 'Muster-Widerrufsformular');
        $this->setLocalization('ger', 'global', 'yourSearch', 'Ihr Suchbegriff lautete:');
        $this->setLocalization('ger', 'productOverview', 'addToCompare', 'Auf die Vergleichsliste');
        $this->setLocalization('ger', 'productOverview', 'addToWishlist', 'Auf den Wunschzettel');
        $this->setLocalization('ger', 'productOverview', 'noResults', 'Leider wurde zu Ihrem Suchbegriff nichts gefunden. Bitte geben Sie einen anderen Suchbegriff ein.');
        $this->setLocalization('ger', 'productOverview', 'previous', 'Zurück');
        $this->setLocalization('ger', 'productOverview', 'ribbon-5', 'Bald verfügbar');
        $this->setLocalization('ger', 'productOverview', 'ribbon-9', 'Vorbestellen');
        $this->setLocalization('ger', 'productOverview', 'searchAgain', 'Erneut suchen');
        $this->setLocalization('ger', 'productDetails', 'addToCompare', 'Auf die Vergleichsliste');
        $this->setLocalization('ger', 'productDetails', 'addToWishlist', 'Auf den Wunschzettel');
        $this->setLocalization('ger', 'productDetails', 'addYourTag', 'Ihren Artikel-Tag hinzufügen');
        $this->setLocalization('ger', 'productDetails', 'basketMatrix', 'Bitte tragen Sie die gewünschten Mengen ein.');
        $this->setLocalization('ger', 'productDetails', 'buyProductBundle', 'Kaufen Sie diesen Artikel im Set!');
        $this->setLocalization('ger', 'productDetails', 'configChooseMaxComponents', 'Bitte wählen Sie maximal %d.');
        $this->setLocalization('ger', 'productDetails', 'configChooseMinComponents', 'Bitte wählen Sie mindestens %d.');
        $this->setLocalization('ger', 'productDetails', 'configChooseNComponents', 'Bitte wählen Sie %d.');
        $this->setLocalization('ger', 'productDetails', 'configChooseOneComponent', 'Bitte wählen Sie genau eine Komponente.');
        $this->setLocalization('ger', 'productDetails', 'configError', 'Es ist ein Fehler bei der Konfiguration aufgetreten. Bitte versuchen Sie es erneut oder wenden Sie sich ggf. an den Support.');
        $this->setLocalization('ger', 'productDetails', 'customerWhoBoughtXBoughtAlsoY', 'Kunden kauften dazu folgende Artikel:');
        $this->setLocalization('ger', 'productDetails', 'dimensions2d', 'Abmessungen (L×H)');
        $this->setLocalization('ger', 'productDetails', 'inStock', 'Auf Lager');
        $this->setLocalization('ger', 'productDetails', 'integralQuantities', 'Bei diesem Artikel ist die Stückzahl teilbar (z. B. 0,5).');
        $this->setLocalization('ger', 'productDetails', 'maximalPurchase', 'Sie können maximal %d %s von diesem Artikel erwerben.');
        $this->setLocalization('ger', 'productDetails', 'minimumPurchase', 'Bitte beachten Sie die Mindestabnahme von %d %s.');
        $this->setLocalization('ger', 'productDetails', 'pleaseChooseVariation', 'Bitte wählen Sie eine Variation.');
        $this->setLocalization('ger', 'productDetails', 'priceForAll', 'Gesamtpreis');
        $this->setLocalization('ger', 'productDetails', 'productOutOfStock', 'Artikel zurzeit vergriffen');
        $this->setLocalization('ger', 'productDetails', 'productQuestion', 'Frage zum Artikel');
        $this->setLocalization('ger', 'productDetails', 'productTags', 'Artikel-Tags');
        $this->setLocalization('ger', 'productDetails', 'productTagsDesc', 'Andere Kunden markierten diesen Artikel mit diesen Tags. Artikel-Tags sind Stichwörter, unter denen andere Kunden die Artikel leichter finden können.');
        $this->setLocalization('ger', 'productDetails', 'productUnsaleable', 'Dieser Artikel ist derzeit nicht verfügbar. Ob und wann dieser Artikel wieder erhältlich ist, steht nicht fest.');
        $this->setLocalization('ger', 'productDetails', 'productVote', 'Bewertungen für diesen Artikel');
        $this->setLocalization('ger', 'productDetails', 'recommendLogin', 'Bitte melden Sie sich an.');
        $this->setLocalization('ger', 'productDetails', 'RelatedProducts', 'Ähnliche Artikel');
        $this->setLocalization('ger', 'productDetails', 'selectionNotAvailable', 'Die gewählte Kombination ist nicht verfügbar.');
        $this->setLocalization('ger', 'productDetails', 'taglogin', 'Anmelden');
        $this->setLocalization('ger', 'productDetails', 'tagloginnow', 'Bitte melden Sie sich an, um dem Artikel einen Tag hinzuzufügen. Artikel-Tags sind Stichwörter, unter denen andere Kunden die Artikel leichter finden können.');
        $this->setLocalization('ger', 'productDetails', 'takeHeedOfInterval', 'Bitte beachten Sie das Abnahmeintervall von %d %s.');
        $this->setLocalization('ger', 'productDetails', 'thisProductIsFrom', 'Dieser Artikel ist erhältlich bei');
        $this->setLocalization('ger', 'productDetails', 'updatingStockInformation', 'Lagerinformationen für Variationen werden geladen…');
        $this->setLocalization('ger', 'checkout', 'additionalCharges', 'Sofern die Lieferung in das Nicht-EU-Ausland erfolgt, können weitere Zölle, Steuern oder Gebühren vom Kunden zu zahlen sein, jedoch nicht an den Anbieter, sondern an die dort zuständigen Zoll- bzw. Steuerbehörden. Wir empfehlen Ihnen, die Einzelheiten vor der Bestellung bei den Zoll- bzw. Steuerbehörden zu erfragen.');
        $this->setLocalization('ger', 'checkout', 'banktransferDesc', 'Wir werden Ihre Bestellung umgehend bearbeiten.');
        $this->setLocalization('ger', 'checkout', 'cancellationPolicyNotice', 'Ich habe die <a href="%s" %s>Widerrufsbelehrung</a> zur Kenntnis genommen.');
        $this->setLocalization('ger', 'checkout', 'cashOnDeliveryDesc', 'Wir werden Ihre Bestellung umgehend versenden.');
        $this->setLocalization('ger', 'checkout', 'checkPLZCity', 'Bitte überprüfen Sie PLZ und Ort.');
        $this->setLocalization('ger', 'checkout', 'creditcardDesc', 'Wir werden Ihre Bestellung umgehend bearbeiten.');
        $this->setLocalization('ger', 'checkout', 'currentCoupon', 'Bereits eingelöster Coupon: ');
        $this->setLocalization('ger', 'checkout', 'discountForArticle', 'Gültig für: ');
        $this->setLocalization('ger', 'checkout', 'doFollowingBanktransfer', 'Bitte führen Sie folgende Überweisung durch:');
        $this->setLocalization('ger', 'checkout', 'emptybasket', 'Es befinden sich keine Artikel im Warenkorb.');
        $this->setLocalization('ger', 'checkout', 'estimateShipping', 'Versandkosten ermitteln');
        $this->setLocalization('ger', 'checkout', 'goOnShopping', 'Weitere Artikel ansehen');
        $this->setLocalization('ger', 'checkout', 'goToStartpage', 'Zur Startseite');
        $this->setLocalization('ger', 'checkout', 'guestOrRegistered', 'Sie können als Gast bestellen oder ein neues Kundenkonto erstellen.');
        $this->setLocalization('ger', 'checkout', 'iban', 'IBAN');
        $this->setLocalization('ger', 'checkout', 'invalidCouponCode', 'Der eingegebene Coupon-Code ist ungültig.');
        $this->setLocalization('ger', 'checkout', 'invalidUserdata', 'Der eingegebene Benutzername und/oder das Passwort ist falsch!');
        $this->setLocalization('ger', 'checkout', 'invoiceDesc', 'Wir werden Ihre Bestellung umgehend bearbeiten.');
        $this->setLocalization('ger', 'checkout', 'loginForRegisteredCustomersDesc', 'Sie haben bereits bei uns bestellt und verfügen über ein Kundenkonto? Dann geben Sie hier Ihre Daten ein.');
        $this->setLocalization('ger', 'checkout', 'minordernotreached', 'Der Mindestbestellwert wurde nicht erreicht. Der Mindestbestellwert beträgt');
        $this->setLocalization('ger', 'checkout', 'missingFilesUpload', 'Bitte laden Sie alle notwendigen Dateien hoch.');
        $this->setLocalization('ger', 'checkout', 'missingProducts', 'Einige Artikel in Ihrem Warenkorb sind bereits vergriffen. Ihr Warenkorb wurde angepasst.');
        $this->setLocalization('ger', 'checkout', 'newEstimation', 'Neue Versandkostenermittlung');
        $this->setLocalization('ger', 'checkout', 'noShippingAvailable', 'Für diesen Zielort stehen keine Versandarten zur Verfügung. Bitte kontaktieren Sie uns direkt, um diese Bestellung abzuwickeln.');
        $this->setLocalization('ger', 'checkout', 'orderCompletedPost', 'Ihre Bestellung ist bei uns eingegangen.');
        $this->setLocalization('ger', 'checkout', 'orderNotPossibleNow', 'Sie haben vor Kurzem bereits eine Bestellung abgeschickt. Weitere Bestellungen sind erst nach 2 Minuten möglich. Wenn Sie vorher versuchen, erneut zu bestellen, wird die Wartezeit verdoppelt.');
        $this->setLocalization('ger', 'checkout', 'orderStep0Title2', 'Wählen Sie die Art, wie Sie bestellen möchten.');
        $this->setLocalization('ger', 'checkout', 'paypalDesc', 'Mit einem Klick auf diese Schaltfläche werden Sie zu PayPal weitergeleitet und können Ihre Bestellung sofort bezahlen.');
        $this->setLocalization('ger', 'checkout', 'priceHasChanged', 'Der Preis des Artikels „%s“ in Ihrem Warenkorb hat sich zwischenzeitlich geändert.  Bitte prüfen Sie die Warenkorbpositionen.');
        $this->setLocalization('ger', 'checkout', 'product', 'Artikel');
        $this->setLocalization('ger', 'checkout', 'productShippingDesc', 'Artikelabhängige Versandkosten');
        $this->setLocalization('ger', 'checkout', 'secureCheckout', 'Sichere Bezahlung');
        $this->setLocalization('ger', 'checkout', 'shippingTo', 'Lieferland');
        $this->setLocalization('ger', 'checkout', 'termsAndConditionsNotice', 'Ich habe die <a href="%s" %s>AGB</a> gelesen und erkläre mit dem Absenden der Bestellung mein Einverständnis.');
        $this->setLocalization('ger', 'checkout', 'useCoupon', 'Coupon einlösen');
        $this->setLocalization('ger', 'checkout', 'wrongBIC', 'Das Format der eingegebenen BIC ist ungültig.');
        $this->setLocalization('ger', 'checkout', 'wrongIban', 'Das Format der eingegebenen IBAN ist ungültig.');
        $this->setLocalization('ger', 'account data', 'birthday', 'Geburtsdatum');
        $this->setLocalization('ger', 'account data', 'birthdayFormat', 'TT.MM.JJJJ');
        $this->setLocalization('ger', 'account data', 'continueOrder', 'Weiter');
        $this->setLocalization('ger', 'account data', 'coupon', 'Coupon einlösen');
        $this->setLocalization('ger', 'account data', 'couponCode', 'Coupon-Code');
        $this->setLocalization('ger', 'account data', 'couponDesc', 'Falls Sie einen Coupon haben und einlösen möchten, geben Sie den Coupon-Code bitte hier ein.');
        $this->setLocalization('ger', 'account data', 'creditDesc', 'Sie haben noch Guthaben auf Ihrem Kundenkonto. Falls Sie es mit dieser Bestellung verrechnen möchten, klicken Sie bitte auf nachfolgende Schaltfläche. ');
        $this->setLocalization('ger', 'account data', 'customerOpenOrders', 'Sie haben noch %d offene Bestellungen%s. Wenn Sie Ihr Kundenkonto jetzt löschen, werden Ihre restlichen Daten automatisch gelöscht, sobald alle Bestellungen abgeschlossen sind.');
        $this->setLocalization('ger', 'account data', 'customerOrdersInCancellationTime', ' und %d Bestellungen, deren Retourenfrist noch nicht abgelaufen ist');
        $this->setLocalization('ger', 'account data', 'emailAlreadyExists', 'Zu der von Ihnen eingegeben E-Mail-Adresse existiert bereits ein Kundenkonto in unserem Onlineshop. Wenn Sie die Bestellung mit Ihrem vorhandenem Kundenkonto abschließen möchten, melden Sie sich bitte mit Ihrer E-Mail-Adresse und Ihrem Passwort an. Wenn Sie als Gast fortfahren möchten, deaktivieren Sie die Option „Neues Kundenkonto erstellen“.');
        $this->setLocalization('ger', 'account data', 'emailNotAvailable', 'Diese E-Mail-Adresse ist bereits vergeben.');
        $this->setLocalization('ger', 'account data', 'formToFast', 'Entschuldigung, Sie sind etwas zu schnell!');
        $this->setLocalization('ger', 'account data', 'invalidCustomer', 'Ungültiger Kunde. Der Kunde ist gesperrt.');
        $this->setLocalization('ger', 'account data', 'invalidHash', 'Ungültiger Hash übergeben. Eventuell ist Ihr Link abgelaufen. Versuchen Sie bitte erneut, Ihr Passwort zurückzusetzen.');
        $this->setLocalization('ger', 'account data', 'newsletterInfo', ', wenn Sie über aktuelle Angebote in unserem Onlineshop informiert werden möchten.');
        $this->setLocalization('ger', 'account data', 'noOrdersYet', 'Sie habe noch keine Bestellung aufgegeben.');
        $this->setLocalization('ger', 'account data', 'noWishlist', 'Es ist kein Wunschzettel vorhanden.');
        $this->setLocalization('ger', 'account data', 'read', 'Lesen');
        $this->setLocalization('ger', 'account data', 'receiverEmail', 'Empfänger-E-Mail-Adresse');
        $this->setLocalization('ger', 'account data', 'receiverName', 'Name des Empfänger');
        $this->setLocalization('ger', 'account data', 'senderEmail', 'Absender-E-Mail-Adresse');
        $this->setLocalization('ger', 'account data', 'senderName', 'Name des Absenders');
        $this->setLocalization('ger', 'account data', 'shippingAdressDesc', 'Falls die Lieferadresse von der Rechnungsadresse abweicht, geben Sie die Rechnungsadresse bitte hier an.');
        $this->setLocalization('ger', 'account data', 'useCredit', 'Verrechnetes Guthaben');
        $this->setLocalization('ger', 'account data', 'wishlists', 'Wunschzettel');
        $this->setLocalization('ger', 'shipping payment', 'accountNo', 'Kontonummer');
        $this->setLocalization('ger', 'shipping payment', 'completeOrder', 'Bestellung abschließen');
        $this->setLocalization('ger', 'shipping payment', 'confirmDataDesc', 'Falls alle Angaben korrekt sind, können Sie die Bestellung abschließen.<br>Sie erhalten eine Bestätigungs-E-Mail von uns.');
        $this->setLocalization('ger', 'login', 'basket2PersMerge', 'Möchten Sie den gespeicherten Warenkorb mit Ihrem aktuellen Warenkorb zusammenfassen?');
        $this->setLocalization('ger', 'login', 'changepasswordPassTooShort', 'Ihr neues Passwort ist zu kurz. Bitte geben Sie ein längeres Passwort ein.');
        $this->setLocalization('ger', 'login', 'changepasswordSuccess', 'Sie haben Ihr Passwort erfolgreich geändert.');
        $this->setLocalization('ger', 'login', 'changepasswordWrongPass', 'Das angegebene alte Passwort ist nicht korrekt. Bitte geben Sie es erneut ein.');
        $this->setLocalization('ger', 'login', 'dataEditSuccessful', 'Die Daten wurden erfolgreich aktualisiert.');
        $this->setLocalization('ger', 'login', 'kwkEmail', 'E-Mail-Adresse');
        $this->setLocalization('ger', 'login', 'kwkName', 'Werben Sie einen Freund!');
        $this->setLocalization('ger', 'login', 'newPasswordRpt', 'Neues Passwort (Wdh.)');
        $this->setLocalization('ger', 'login', 'notPayedYet', 'Noch kein Zahlungseingang');
        $this->setLocalization('ger', 'login', 'notShippedYet', 'Noch nicht versendet');
        $this->setLocalization('ger', 'login', 'orderNo', 'Bestellnummer');
        $this->setLocalization('ger', 'login', 'passwordhasUsername', 'Das Passwort darf den Namen des Benutzers nicht enthalten.');
        $this->setLocalization('ger', 'login', 'passwordIsMedium', 'Mittel; versuchen Sie, Sonderzeichen zu verwenden.');
        $this->setLocalization('ger', 'login', 'reallyDeleteAccount', 'Möchten Sie Ihr Kundenkonto wirklich unwiderruflich löschen?');
        $this->setLocalization('ger', 'login', 'trackingId', 'Sendungsverfolgungsnummer');
        $this->setLocalization('ger', 'login', 'typeYourPassword', 'Bitte geben Sie ein Passwort ein.');
        $this->setLocalization('ger', 'login', 'wishlistEmailCount', 'Maximale Anzahl der E-Mail-Empfänger');
        $this->setLocalization('ger', 'login', 'wishlistEmails', 'E-Mail-Empfänger – getrennt durch Leerzeichen');
        $this->setLocalization('ger', 'login', 'wishlistNotPrivat', 'Wunschzettel auf „Öffentlich“ setzen');
        $this->setLocalization('ger', 'login', 'wishlistPrivat', 'Wunschzettel auf „Privat“ setzen');
        $this->setLocalization('ger', 'login', 'wishlistPublic', 'Öffentlich');
        $this->setLocalization('ger', 'login', 'wishlistremoveItem', 'Artikel entfernen');
        $this->setLocalization('ger', 'login', 'wishlistRemoveSearch', 'Suche löschen');
        $this->setLocalization('ger', 'login', 'wishlistSaveNew', 'Erstellen');
        $this->setLocalization('ger', 'login', 'wishlistSetPrivate', 'Auf „Privat“ setzen');
        $this->setLocalization('ger', 'login', 'wishlistSetPublic', 'Auf „Öffentlich“ setzen');
        $this->setLocalization('ger', 'login', 'wishlistURL', 'Link zu Ihrem Wunschzettel:');
        $this->setLocalization('ger', 'forgot password', 'createNewPassword', 'Neues Passwort anfordern');
        $this->setLocalization('ger', 'forgot password', 'forgotPasswordDesc', 'Bitte geben Sie hier die E-Mail-Adresse ein, mit der Sie sich registriert haben.');
        $this->setLocalization('ger', 'contact', 'youSentUsAMessageShortTimeBefore', 'Sie haben uns vor kurzer Zeit bereits eine Nachricht geschickt. Bitte warten Sie einen Moment, bevor Sie uns erneut eine Nachricht schicken.');
        $this->setLocalization('ger', 'comparelist', 'addtowishlist', 'Auf den Wunschzettel');
        $this->setLocalization('ger', 'comparelist', 'back', 'Zurück zum Onlineshop');
        $this->setLocalization('ger', 'comparelist', 'productNumberHint', 'Bitte fügen Sie mindestens zwei Artikel zur Vergleichsliste hinzu.');
        $this->setLocalization('ger', 'comparelist', 'weightUnit', 'kg');
        $this->setLocalization('ger', 'product rating', 'allreadyWroteReview', 'Sie haben bereits eine Bewertung zu diesem Artikel abgegeben.');
        $this->setLocalization('ger', 'product rating', 'feedback activated', 'Bewertung ist freigeschaltet.');
        $this->setLocalization('ger', 'product rating', 'feedback deactivated', 'Bewertung ist noch nicht freigeschaltet.');
        $this->setLocalization('ger', 'product rating', 'isRatingHelpful', 'Ist diese Bewertung hilfreich für Sie?');
        $this->setLocalization('ger', 'product rating', 'latestReviewFirst', 'Älteste zuerst');
        $this->setLocalization('ger', 'product rating', 'maxProduct1', 'Es liegen');
        $this->setLocalization('ger', 'product rating', 'shareYourExperience', 'Teilen Sie anderen Kunden Ihre Erfahrungen mit!');
        $this->setLocalization('ger', 'product rating', 'shareYourRatingGuidelines', 'Teilen Sie uns Ihre Meinung mit!');
        $this->setLocalization('ger', 'product rating', 'unusefulClassifiedReviewFirst', 'Als „Nicht hilfreich“ eingestufte zuerst');
        $this->setLocalization('ger', 'product rating', 'usefulClassifiedReviewFirst', 'Als „Hilfreich“ eingestufte zuerst');
        $this->setLocalization('ger', 'newsletter', 'newsletterhistoryback', 'Zurück');
        $this->setLocalization('ger', 'newsletter', 'newsletterHtml', 'Inhalt (HTML)');
        $this->setLocalization('ger', 'newsletter', 'newsletterSendSubscribe', 'Abonnieren');
        $this->setLocalization('ger', 'newsletter', 'newsletterSendUnsubscribe', 'Abmelden');
        $this->setLocalization('ger', 'newsletter', 'newsletterSubscribeDesc', 'Um sich für unseren Newsletter anzumelden, tragen Sie bitte hier Ihre E-Mail-Adresse ein und klicken anschließend auf „Abonnieren“.');
        $this->setLocalization('ger', 'newsletter', 'newsletterUnsubscribeDesc', 'Um sich vom Newsletter abzumelden, tragen Sie bitte Ihre E-Mail-Adresse in das untenstehende Feld ein. Klicken Sie anschließend auf „Abmelden“.');
        $this->setLocalization('ger', 'newsletter', 'unsubscribeAnytime', 'Abonnieren Sie jetzt den Newsletter und verpassen Sie keine Angebote. Die Abmeldung ist jederzeit möglich.');
        $this->setLocalization('ger', 'news', 'monthOverview', 'News: Monate mit Beiträgen');
        $this->setLocalization('ger', 'news', 'moreLink', 'Weiter');
        $this->setLocalization('ger', 'news', 'newsCat', 'Kategorie des News-Systems');
        $this->setLocalization('ger', 'news', 'newsCatOverview', 'Übersicht der Kategorien des News-Systems');
        $this->setLocalization('ger', 'news', 'newsCats', 'Kategorien des News-Systems');
        $this->setLocalization('ger', 'news', 'newsCommentSave', 'Speichern');
        $this->setLocalization('ger', 'news', 'newsMonthOverview', 'News: Monate mit Beiträgen');
        $this->setLocalization('ger', 'news', 'newsSortCommentsASC', 'Kommentarzahl aufsteigend');
        $this->setLocalization('ger', 'news', 'newsSortCommentsDESC', 'Kommentarzahl absteigend');
        $this->setLocalization('ger', 'news', 'newsSortHeadlineASC', 'Überschrift A–Z');
        $this->setLocalization('ger', 'news', 'newsSortHeadlineDESC', 'Überschrift Z–A');
        $this->setLocalization('ger', 'news', 'noNewsArchiv', 'Leider befinden sich noch keine News-Beiträge im Archiv.');
        $this->setLocalization('ger', 'news', 'overview', 'News-Übersicht');
        $this->setLocalization('ger', 'strength', 'stronger', 'sehr stark');
        $this->setLocalization('ger', 'breadcrumb', 'bcWishlist', 'Wunschzettel');
        $this->setLocalization('ger', 'breadcrumb', 'login', 'Anmeldung');
        $this->setLocalization('ger', 'breadcrumb', 'newskat', 'Kategorie des News-Systems');
        $this->setLocalization('ger', 'breadcrumb', 'newsmonat', 'News-Monat');
        $this->setLocalization('ger', 'breadcrumb', 'wishlist', 'Wunschzettel');
        $this->setLocalization('ger', 'basket', 'noShippingCostsAtExtended', 'nach %s.');
        $this->setLocalization('ger', 'basket', 'noShippingCostsReached', 'Ihre Bestellung ist mit %s versandkostenfrei %s lieferbar.');
        $this->setLocalization('ger', 'basket', 'orderExpandInventory', 'Folgende Artikel sind in der gewählten Menge nicht verfügbar und die Lieferung könnte sich aufgrund dessen verzögern: %s');
        $this->setLocalization('ger', 'order', 'openPartialShipped', 'Offene Teillieferungen');
        $this->setLocalization('ger', 'order', 'partialShipped', 'Teillieferung');
        $this->setLocalization('ger', 'order', 'statusPaid', 'Bezahlt');
        $this->setLocalization('ger', 'order', 'statusPartialShipped', 'Teilgeliefert');
        $this->setLocalization('ger', 'order', 'statusPending', 'Offen');
        $this->setLocalization('ger', 'order', 'statusProcessing', 'In Bearbeitung');
        $this->setLocalization('ger', 'order', 'statusShipped', 'Versendet');
        $this->setLocalization('ger', 'messages', 'accountDeleted', 'Das Kundenkonto wurde erfolgreich gelöscht.');
        $this->setLocalization('ger', 'messages', 'artikelVariBoxEmpty', 'Bitte geben Sie mindestens die Artikelmenge in der Variationsbox ein.');
        $this->setLocalization('ger', 'messages', 'availAgainOptinCreated', 'Vielen Dank, wir haben Ihre Daten erhalten. Wir haben Ihnen eine E-Mail mit einem Freischaltcode zugeschickt. Bitte klicken Sie auf den Link in der E-Mail, um informiert zu werden, sobald der Artikel wieder verfügbar ist.');
        $this->setLocalization('ger', 'messages', 'basketAjaxAdded', 'Der Artikel %s wurde Ihrem Warenkorb hinzugefügt. (%dx)');
        $this->setLocalization('ger', 'messages', 'bewertungBewaddacitvate', 'Ihre Bewertung wurde eingetragen und muss nun vom Verkäufer freigeschaltet werden.');
        $this->setLocalization('ger', 'messages', 'bewertungBewaddCredits', 'Ihre Bewertung wurde eingetragen und Ihnen wurde %s € auf Ihr Kundenkonto gutgeschrieben.');
        $this->setLocalization('ger', 'messages', 'chooseVariations', 'Dieser Artikel hat Variationen. Wählen Sie bitte die gewünschte Variation aus.');
        $this->setLocalization('ger', 'messages', 'comparelistProductadded', 'Ihr ausgewählter Artikel wurde der Vergleichsliste hinzugefügt.');
        $this->setLocalization('ger', 'messages', 'continueAfterActivation', 'Sie können mit dem Bestellprozess fortfahren, sobald Ihr Kundenkonto freigeschaltet wurde.');
        $this->setLocalization('ger', 'messages', 'loginWishlist', 'Bitte melden Sie sich an, um dem Wunschzettel Artikel hinzuzufügen.');
        $this->setLocalization('ger', 'messages', 'maxTagsExceeded', 'Entschuldigung, Sie haben bereits die innerhalb von 24 Stunden erlaubte Anzahl an Artikel-Tags hinzugefügt.');
        $this->setLocalization('ger', 'messages', 'newscommentAddactivate', 'Ihr Kommentar wurde erfolgreich gespeichert und muss nun vom Verkäufer freigeschaltet werden.');
        $this->setLocalization('ger', 'messages', 'newsletterAdd', 'Vielen Dank, wir haben Ihre Daten erhalten. Wir haben Ihnen eine E-Mail mit einem Freischalt-Code zugeschickt. Bitte klicken Sie auf den Link in der E-Mail, um Ihre Anmeldung zum Newsletter erfolgreich abzuschließen.');
        $this->setLocalization('ger', 'messages', 'newsletterNomailAdd', 'Vielen Dank, Sie wurden in die Verteilerliste für den Newsletter-Versand eingetragen.');
        $this->setLocalization('ger', 'messages', 'nowlidWishlist', 'Der Wunschzettel mit der ID „%s“ ist entweder nicht mehr öffentlich oder wurde gelöscht.');
        $this->setLocalization('ger', 'messages', 'optinCanceled', 'Ihre Einwilligung wurde aufgehoben.');
        $this->setLocalization('ger', 'messages', 'optinRemoved', 'Ihr Freischaltantrag wurde gelöscht.');
        $this->setLocalization('ger', 'messages', 'optinSucceededMailSent', 'Es wurde bereits eine E-Mail mit Ihrem Freischalt-Code an Sie verschickt.');
        $this->setLocalization('ger', 'messages', 'pleaseLogin', 'Bitte melden Sie sich an, um in unserem Onlineshop einzukaufen.');
        $this->setLocalization('ger', 'messages', 'pleaseLoginToAddTags', 'Bitte melden Sie sich an, um Artikel-Tags hinzuzufügen.');
        $this->setLocalization('ger', 'messages', 'pollCoupon', 'Vielen Dank für die Teilnahme an unserer Umfrage. Für Ihre nächste Bestellung steht Ihnen der folgende Coupon-Code zur Verfügung: %s.');
        $this->setLocalization('ger', 'messages', 'pollCredit', 'Vielen Dank für die Teilnahme an unserer Umfrage. Ihnen wurde ein Guthaben von %s gutgeschrieben.');
        $this->setLocalization('ger', 'messages', 'pollError', 'Bei der Auswertung ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.');
        $this->setLocalization('ger', 'messages', 'preorderNotPossible', 'Eine Vorbestellung dieses Artikels ist leider nicht möglich.');
        $this->setLocalization('ger', 'messages', 'quantityNotAvailable', 'Die gewünschte Artikelmenge ist leider nicht verfügbar. Bitte geben Sie eine kleinere Menge an.');
        $this->setLocalization('ger', 'messages', 'quantityNotAvailableVar', 'Die gewünschte Artikelmenge ist in der gewählten Variation leider nicht verfügbar. Bitte geben Sie eine kleinere Menge an oder wählen Sie eine andere Variation aus.');
        $this->setLocalization('ger', 'messages', 'questionNotPossible', 'Sie haben erst kürzlich eine Frage zum Artikel abgeschickt. Bitte warten Sie einige Zeit, um eine neue Frage zum Artikel zu versenden.');
        $this->setLocalization('ger', 'messages', 'tagAccepted', 'Der Artikel-Tag wurde hinzugefügt.');
        $this->setLocalization('ger', 'messages', 'tagAcceptedWaitCheck', 'Ihr Artkel-Tag wurde hinzugefügt und wird vom Administrator geprüft.');
        $this->setLocalization('ger', 'messages', 'tagArtikelEmpty', 'Bitte geben Sie einen Namen für den Artikel-Tag ein.');
        $this->setLocalization('ger', 'messages', 'thankYouForNotificationSubscription', 'Vielen Dank. Wir werden Sie umgehend benachrichtigen, sobald der Artikel wieder verfügbar ist.');
        $this->setLocalization('ger', 'messages', 'thankYouForQuestion', 'Vielen Dank für Ihre Frage zum Artikel.');
        $this->setLocalization('ger', 'messages', 'wishlistProductadded', 'Der ausgewählte Artikel wurde zu Ihrem Wunschzettel hinzugefügt.');
        $this->setLocalization('ger', 'messages', 'wkMaxorderlimit', 'Die Bestellmenge für diesen Artikel ist leider zu hoch.');
        $this->setLocalization('ger', 'messages', 'wkOnrequest', 'Artikelpreis auf Anfrage');
        $this->setLocalization('ger', 'messages', 'wkPurchaseintervall', 'Die Bestellmenge für diesen Artikel muss ein Vielfaches des Abnahmeintervalls sein.');
        $this->setLocalization('ger', 'errorMessages', 'bewertungBewexist', 'Sie haben bereits eine Bewertung zu diesem Artikel abgegeben.');
        $this->setLocalization('ger', 'errorMessages', 'cartPersRemoved', 'Der Artikel „%s“ konnte nicht in den Warenkorb übernommen werden.');
        $this->setLocalization('ger', 'errorMessages', 'compareMaxlimit', 'Entschuldigung, Ihre Vergleichsliste hat die maximale Anzahl an Artikeln erreicht. Bitte entfernen Sie Artikel von der Vergleichsliste, um neue Artikel hinzuzufügen. ');
        $this->setLocalization('ger', 'errorMessages', 'freegiftsMinimum', 'Der für das Gratisgeschenk benötigte Mindestbestellwert ist noch nicht erreicht.');
        $this->setLocalization('ger', 'errorMessages', 'kwkAlreadyreg', 'Die E-Mail-Adresse %s wird bereits verwendet.');
        $this->setLocalization('ger', 'errorMessages', 'kwkEmailblocked', 'Diese E-Mail-Adresse ist gesperrt.');
        $this->setLocalization('ger', 'errorMessages', 'kwkWrongdata', 'Bitte geben Sie gültige Daten ein.');
        $this->setLocalization('ger', 'errorMessages', 'mandatoryFieldNotification', 'Bitte füllen Sie alle Pflichtfelder aus.');
        $this->setLocalization('ger', 'errorMessages', 'missingParamShippingDetermination', 'Bitte füllen Sie die Angaben zu Land und Postleitzahl korrekt aus.');
        $this->setLocalization('ger', 'errorMessages', 'missingTaxZoneForDeliveryCountry', 'Ein Versand nach %s ist aktuell nicht möglich, da keine gültige Steuerzone hinterlegt ist.');
        $this->setLocalization('ger', 'errorMessages', 'newscommentAlreadywritten', 'Sie haben bereits die maximale Anzahl an Kommentaren zu diesem News-Beitrag erreicht.');
        $this->setLocalization('ger', 'errorMessages', 'newscommentLongtext', 'Sie haben die maximale Zeichenzahl von 1000 Zeichen für den Kommentartext überschritten.');
        $this->setLocalization('ger', 'errorMessages', 'newscommentMissingnameemail', 'Bitte geben Sie einen Namen sowie eine E-Mail-Adresse ein.');
        $this->setLocalization('ger', 'errorMessages', 'newscommentMissingtext', 'Bitte geben Sie einen Text ein.');
        $this->setLocalization('ger', 'errorMessages', 'newsletterCaptcha', 'Bitte beachten Sie das Captcha.');
        $this->setLocalization('ger', 'errorMessages', 'newsletterNoactive', 'Der Freischalt-Code wurde nicht gefunden.');
        $this->setLocalization('ger', 'errorMessages', 'newsletterNocode', 'Ihr Lösch-Code konnte nicht in der Datenbank gefunden werden. Bitte überprüfen Sie die Eingabe auf eventuelle Tippfehler oder wenden Sie sich ggf. an den Support.');
        $this->setLocalization('ger', 'errorMessages', 'newsletterNoexists', 'Ihre E-Mail-Adresse ist nicht in der Datenbank vorhanden. Bitte überprüfen Sie die Eingabe auf eventuelle Tippfehler oder wenden Sie sich ggf. an den Support.');
        $this->setLocalization('ger', 'errorMessages', 'newsletterNoname', 'Bitte geben Sie einen Vor- und Nachnamen ein.');
        $this->setLocalization('ger', 'errorMessages', 'newsletterWrongemail', 'Entschuldigung, Ihre E-Mail-Adresse weist ein ungültiges Format auf.');
        $this->setLocalization('ger', 'errorMessages', 'noCookieDesc', 'Zur Nutzung unserer Seite müssen Sie im Browser Cookies aktivieren.<br />Rufen Sie dann noch einmal unsere <a href="index.php">Startseite</a> auf.');
        $this->setLocalization('ger', 'errorMessages', 'noCookieHeader', 'Cookies aktivieren');
        $this->setLocalization('ger', 'errorMessages', 'noMediaFile', 'Es sind keine Mediendateien vorhanden.');
        $this->setLocalization('ger', 'errorMessages', 'optinActionUnknown', 'Unbekannte Aktion angefordert. Bitte wenden Sie sich an den Support.');
        $this->setLocalization('ger', 'errorMessages', 'optinCodeUnknown', 'Der eingegebene Bestätigungscode ist nicht bekannt. Bitte überprüfen Sie die Eingabe auf eventuelle Tippfehler oder wenden Sie sich ggf. an den Support.');
        $this->setLocalization('ger', 'errorMessages', 'pollAlreadydid', 'Entschuldigung, Sie haben bereits an dieser Umfrage teilgenommen.');
        $this->setLocalization('ger', 'errorMessages', 'pollRequired', 'Bitte geben Sie alle erforderlichen Antworten.');
        $this->setLocalization('ger', 'errorMessages', 'productquestionPleaseLogin', 'Entschuldigung, Sie müssen angemeldet sein, um eine Frage zum Artikel zu versenden.');
        $this->setLocalization('ger', 'errorMessages', 'ratingRange', 'Die Bewertung muss eine Zahl von 1 bis 5 sein.');
        $this->setLocalization('ger', 'errorMessages', 'statusOrderNotFound', 'Es wurde keine passende Bestellung gefunden.');
        $this->setLocalization('ger', 'errorMessages', 'uidNotFound', 'Es wurde keine Bestellung zu der angeforderten ID gefunden.');
        $this->setLocalization('ger', 'redirect', 'tag', 'Artikel-Tag');
        $this->setLocalization('ger', 'redirect', 'wishlist', 'Wunschzettel');
        $this->setLocalization('ger', 'paymentMethods', 'errorMailBody', 'In Ihrem Onlineshop %s ist bei Bestellung %s beim Initialisieren des Bezahlvorgangs mit der Zahlungsart %s folgender Fehler aufgetreten: %s.');
        $this->setLocalization('ger', 'paymentMethods', 'errorMailSubject', 'Fehler in Ihrem Onlineshop %s');
        $this->setLocalization('ger', 'paymentMethods', 'errorText', 'Beim Initialisieren des Bezahlvorgangs ist ein Fehler aufgetreten. Der Onlineshop-Betreiber wurde benachrichtigt und wird sich mit Ihnen in Verbindung setzen.');
        $this->setLocalization('ger', 'paymentMethods', 'paypalError', 'Bei der Kommunikation mit PayPal ist ein Fehler aufgetreten. Möglicherweise ist Ihr PayPal-Konto noch nicht freigeschaltet. Falls das nicht der Fall ist, wenden Sie sich bitte mit folgendem Fehlercode an den Betreiber des Onlineshops: %s');
        $this->setLocalization('ger', 'paymentMethods', 'paypalText', 'Bezahlen Sie Ihre Bestellung %s von %s.');
        $this->setLocalization('ger', 'rma', 'rma_error_alreadysend', 'Sie haben bereits zu einigen ausgewählten Artikeln eine Rücksendenummer (RMA) abgesendet.');
        $this->setLocalization('ger', 'rma', 'rma_error_noarticle', 'Bitte markieren Sie mindestens einen Artikel.');
        $this->setLocalization('ger', 'rma', 'rma_error_validquantity', 'Vergewissern Sie sich, dass Sie eine Artikelmenge angegeben haben und diese nicht die bestellte Menge überschreitet.');
        $this->setLocalization('ger', 'rma', 'rma_go', 'Los');
        $this->setLocalization('ger', 'rma', 'rma_info_success', 'Die Warenrücksendung mit Nummer %s wurde erfolgreich gespeichert.');
        $this->setLocalization('ger', 'rma', 'rma_login', 'Bitte melden Sie sich an, um eine Warenrücksendung durchzuführen.');
        $this->setLocalization('ger', 'rma', 'rma_nolicence', 'Es wurde keine gültige Lizenz für dieses Modul gefunden.');
        $this->setLocalization('ger', 'rma', 'rma_number', 'Rücksendenummer');
        $this->setLocalization('ger', 'rma', 'rma_success_msg_1', 'Vielen Dank, dass Sie unsere Warenrücksendung nutzen.<br /><br />Im Folgenden finden Sie eine Übersicht über Ihre zur Rücksendung ausgewählten Artikel.');
        $this->setLocalization('ger', 'rma', 'rma_success_msg_2', 'Bitte drucken Sie diese aus und legen sie Ihrem Rücksendepaket bei.<br /><br />Sobald wir Ihre Rücksendung verarbeitet haben, benachrichtigen wir Sie per E-Mail über die Erstattung (sofern zutreffend).<br /><br />Vielen Dank für Ihren Einkauf bei');
        $this->setLocalization('ger', 'wishlist', 'setAsStandardWishlist', 'Lassen Sie neue Artikel standardmäßig auf den aktuell gewählten Wunschzettel setzen.');
        $this->setLocalization('ger', 'wishlist', 'wlDelete', 'Wunschzettel löschen');
    }

    /**
     * @return mixed|void
     */
    public function down()
    {
    }
}
