<?php declare(strict_types=1);

namespace JTL\ChangeMe;

use Exception;
use JTL\Model\DataAttribute;
use JTL\Model\DataModel;

/**
 * Class TWarengruppeModel
 * This class is generated by shopcli model:create
 *
 * @package JTL\ChangeMe
 * @property int $kWarengruppe
 * @method int getKWarengruppe()
 * @method void setKWarengruppe(int $value)
 * @property string $cName
 * @method string getCName()
 * @method void setCName(string $value)
 */
final class TWarengruppeModel extends DataModel
{
    /**
     * @inheritdoc
     */
    public function getTableName(): string
    {
        return 'twarengruppe';
    }

    /**
     * Setting of keyname is not supported!
     * Call will always throw an Exception with code ERR_DATABASE!
     * @inheritdoc
     */
    public function setKeyName($keyName): void
    {
        throw new Exception(__METHOD__ . ': setting of keyname is not supported', self::ERR_DATABASE);
    }

    /**
     * @inheritdoc
     */
    protected function onRegisterHandlers(): void
    {
        parent::onRegisterHandlers();
    }

    /**
    * @inheritdoc
    */
    public function getAttributes(): array
    {
        static $attributes = null;
        if ($attributes === null) {
            $attributes   = [];
            $attributes['kWarengruppe'] = DataAttribute::create('kWarengruppe', 'int', null, false, true);
            $attributes['cName'] = DataAttribute::create('cName', 'varchar', null, true, false);
        }

        return $attributes;
    }
}
